<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.ML.Tokenizers" />
    <PackageReference Include="OllamaSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../MafPlayground.AI/MafPlayground.AI.csproj" />
    <ProjectReference Include="../MafPlayground.Retrieval/MafPlayground.Retrieval.csproj" />
  </ItemGroup>

</Project>
